server:
  port: 8081
spring:
  profiles: dev
  application:
    name: animal-inventory
  datasource:
    url: "${SPRING_DATASOURCE_URL}"
    username: "${SPRING_USERNAME_URL}"
    password: "${SPRING_PASSWORD_URL}"
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    hibernate:
      ddl-auto: create
