server:
  port: 8081
spring:
  profiles: dev
  application:
    name: animal-inventory
  datasource:
    url: jdbc:postgresql://db:5432/compose-postgres
    username: "${db-username}"
    password: "${db-password}"
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    hibernate:
      ddl-auto: create
